# Create new input directory on HDFS and copy input files from local
# filesystem to HDFS filesystem.
hadoop fs -rm -r input/PageRank
hadoop fs -mkdir -p input/PageRank
hadoop fs -put input/* input/PageRank


# Create new output directories on HDFS and delete existing output 
# directories generated by previous execution instance of 
# MapReduce application.
hadoop fs -mkdir -p output/MapReduce2/PageRank
hadoop fs -rm -r output/MapReduce2/PageRank


# Compile source code and create a jar file.
javac -cp /usr/lib/hadoop/*:/usr/lib/hadoop-mapreduce/*:/usr/lib/hadoop-0.20-mapreduce/* src/org/myorg/pagerank/*.java -d bin -Xlint
jar -cvf PageRank.jar -C bin/ .


# Run MapReduce application on HDFS.
hadoop jar PageRank.jar org.myorg.pagerank.WikiPageRank "10" "0.85" "100" input/PageRank output/MapReduce2/PageRank/TopWikiPage false


# Get final output from HDFS.
rm -r PageRank/
hadoop fs -get output/MapReduce2/PageRank/
